Experimental signal-handling (apparently working)
NOTE: one can now use Ctrl-C in the original terminal to terminate everything
NOTE: killing any of `exhibit-*` will trigger restart, while killing `hidecursor` or `repeat-exhibit` will trigger total termination

diff --git a/bin/hidecursor b/bin/hidecursor
--- a/bin/hidecursor
+++ b/bin/hidecursor
@@ -2,8 +2,45 @@
 # This script is supposed to hide the cursor while the "$@" is running.
 # Afterwards the cursor must be visible again (i.e. xbanish must have exited).
 
-trap "trap - SIGTERM && kill -- -$$ >/dev/null 2>&1" SIGINT SIGTERM EXIT
+#trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
+
+PID="0"
+PID_CMD="0"
+
 xbanish &
+PID="${!}"
+
+function xbanish_handler(){
+#  echo "xbanish_handler[$@]!"
+#  ps f
+  if [[ "$PID" != 0 ]]; then
+    kill -- "${PID}" 1>/dev/null 2>&1
+    PID="0"
+  fi
+
+  if [[ "${PID_CMD}" != 0 ]]; then
+    kill -- "${PID_CMD}" 1>/dev/null 2>&1
+    PID_CMD="0"
+  fi
+
+  trap - SIGTERM
+#  kill -- -$BASHPID
+  kill -- -$$ 1>/dev/null 2>&1
+  kill 0 1>/dev/null 2>&1
+#  ps f
+#  echo "....xbanish_handler!"
+  exit # NOTE: ANY SIGNAL => FINISH!!!
+}
+
+for sig in INT TERM QUIT EXIT; do
+  eval "trap 'xbanish_handler ${sig}' $sig"
+done
+
 
 # Don't use exec here because the user must still to be able to ps | grep for hidecursor.
-"$@"
+eval "$@" &
+PID_CMD="${!}"
+wait
+# return/propagate exit code
+
+# ps f
diff --git a/bin/repeat-exhibit b/bin/repeat-exhibit
--- a/bin/repeat-exhibit
+++ b/bin/repeat-exhibit
@@ -3,5 +3,41 @@
 # When the script is terminated from outside, the loop must
 # end as well as the process running inside the loop
 
-trap "trap - SIGTERM && kill -- -$$ >/dev/null 2>&1" SIGINT SIGTERM EXIT
-while true; do "$@"; done
+#trap "trap - SIGTERM && kill -- -$$ >/dev/null 2>&1" SIGINT SIGTERM EXIT
+
+PID="0"
+EXIT="0"
+
+function repeat_handler(){
+#  echo "repeat_handler[$@]!"
+#  ps f
+  if [[ "$PID" != 0 ]]; then
+    kill -- "${PID}" >/dev/null 2>&1
+    PID="0"
+  fi
+  EXIT="1"
+
+  trap - SIGTERM
+#  kill -- -$BASHPID
+  kill -- -$$ >/dev/null 2>&1
+  kill 0 >/dev/null 2>&1
+#  ps f
+#  echo "....repeat_handler!"
+  exit # NOTE: ANY SIGNAL => FINISH!!!
+}
+
+for sig in INT TERM QUIT EXIT; do
+  eval "trap 'repeat_handler ${sig}' $sig"
+done
+
+
+while [[ "${EXIT}" = "0" ]]; do 
+  eval "$@" &
+  PID="${!}"
+  wait
+  # exit code return/propagate!?
+  PID="0"
+  sleep 0.1
+done
+
+# ps f
